services:
  fcp-fd-messages-processor:
    build:
      context: .
      target: production
    image: fcp-fd-messages-processor
    container_name: fcp-fd-messages-processor
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-messages-processor-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
