# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-messages-processor:
    build:
      target: development
    image: fcp-fd-messages-processor-development
    container_name: fcp-fd-messages-processor-development
    ports:
      - "3035:3035"
      - "9035:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
